### ISSUE TITLE
Not working with dynamic data.

### ISSUE THREAD

**Issue by jacobbutton** [HaithemMosbahi/ngx-avatar#1]
Component will work with static data but doesn't update with dynamic data loaded via an async call to a service on pageload.

`<ngx-avatar name="{{user.name}}" bgColor="{{user.color}}" size="250"></ngx-avatar>`

`ngOnInit() {
        this.userService.get(this.userId).subscribe( u => { this.user = u; });
}`

**Comment by HaithemMosbahi** [comment]
Thank you for raising this issue.
I will fix this problem today by adding support to dynamic data and detecting input changes.

**Comment by HaithemMosbahi** [comment]
I've added change detection to avatar inputs. Now you can provides the avatar with dynamic data.
It took me some time to fix this because the component can work with multiple avatar sources. Thus, a change that occurs in input that represents a source ( facebook, twitter, name initials, etc ) should also update the fallback system.
Also, I've updated the demo application with an example that loads avatar data asynchronously.

**Comment by HaithemMosbahi** [comment]
This bug is fixed on version 1.3.0

**Comment by jacobbutton** [comment]
Just tried the new version. It's working as expected.

Thank you. Great component.

**Comment by HaithemMosbahi** [comment]
Great. You're welcome :)
