### ISSUE TITLE
Adding of Mistery man in d=404 gravatar

### ISSUE THREAD

**Issue by roger-edesigns** [HaithemMosbahi/ngx-avatar#26]
So much thanks if you add the Mistery man and not a 404 broken image

**Comment by HaithemMosbahi** [comment]
You can achieve this with the current implementation of the avatar component. Here is an example that  would show facebook avatar if it's successfully loaded and fallback to the image that was provided as src otherwise 
`<ngx-avatar facebookId="userFacebookID" src="assets/avatar.jpg"` > </ngx-avatar>

Let me know if you still have any problem with this.
