### ISSUE TITLE
Element structure and styling

### ISSUE THREAD

**Issue by bhalperin** [HaithemMosbahi/ngx-avatar#6]
Hi,

The element structure that you generate is
```
<ngx-avatar>
   <div>
      <div>
      </div>
   </div>
</ngx-avatar>
```
You apply the styling on both ```<div>``` elements, which is unnecessary and creates undesired effects when for instance I set the border gray it renders both ```<div>``` elements with gray border (example below). Applying only on one of them seems the right way to do it.

Also, I think you should give each ```<div>``` a CSS class name to provide maximum customization power.

**See right avatar:**

![image](https://user-images.githubusercontent.com/683900/29134096-4988a368-7d3e-11e7-975d-45f18f7471df.png)

**Styling with [style] attribute:**

```
{
    backgroundColor: "#ffffff",
    border: "1px solid #7e7e7e",
    borderRadius: "50%",
    color: "#7e7e7e",
    cursor: "pointer"
}
```

**Comment by HaithemMosbahi** [comment]
Hi, 

Thank you for your suggestions. Yes, I can totally check this out and reorganize the element's style.

**Comment by HaithemMosbahi** [comment]
Style was applied twice for initials avatar. I've removed the unnecessary style and kept the style on the host element because it is applied to both types of avatar ( image & text ).
Also, I've added css classes to provide more customization capabilities.
the bug fix and the new css classes will be included in the next version which will be released tomorrow 😃
